name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      - name: Type check server
        working-directory: server
        env:
          DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy
        run: |
          npm ci
          npx prisma generate
          npx tsc --noEmit

      - name: Type check client
        working-directory: client
        run: |
          npm ci
          npx tsc --noEmit

      - name: Deploy
        run: |
          cd ~/JobTracker

          # Pull latest code
          git pull origin main
          # Rebuild and restart container with zero downtime
          docker compose up --build -d
          # Remove unused images to free disk space
          docker image prune -f
          # Confirm all container are running
          docker compose ps
